FROM registry.access.redhat.com/ubi9/go-toolset:1.24 AS build
WORKDIR /src
COPY go.mod go.sum* ./
RUN go mod download
COPY cmd/webserver ./cmd/webserver
RUN CGO_ENABLED=0 go build -ldflags "-s -w" -o /tmp/dasm-burner-web ./cmd/webserver

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
COPY --from=build /tmp/dasm-burner-web /usr/local/bin/dasm-burner-web
USER 65532
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/dasm-burner-web"]
